name: Homescapes UI Autotests
run-name: 🤖 Running Homescapes UI Autotests
on: 
  workflow_dispatch:
    inputs:     
      AUTOTESTS_BRANCH: 
        description: homescapes_autotests branch
        default: "main"
      
      TEAMCITY_BUILD_ID: 
        description: Teamcity build id
        default: "18408273"
    
      PLATFORM:
        description: Platform
        default: "android"
      
      ONLY_TESTING:
        description: Only testing
        default: "8075"
      
      RETRIES: 
        description: Retries
        default: "3"
      
      PARALLEL_THREADS: 
        description: Parallel threads
        default: "1"
jobs:
  PLR-HS-QA-AUTOTESTS:
    strategy:
      matrix:
        runner: [aqa_hs_0]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: TestQaCI
        shell: bash -l {0}
        env: 
          LANG: "en_US.UTF-8"
          LANGUAG: "en_US.UTF-8"
          LC_ALL: "en_US.UTF-8"
          AUTOTESTS_BRANCH: "${{github.event.inputs.AUTOTESTS_BRANCH}}"
          TEAMCITY_BUILD_ID: "${{github.event.inputs.TEAMCITY_BUILD_ID}}"
          PLATFORM: "${{github.event.inputs.PLATFORM}}"
          ONLY_TESTING: "${{github.event.inputs.ONLY_TESTING}}"
          RETRIES: "${{github.event.inputs.RETRIES}}"
          PARALLEL_THREADS: "${{github.event.inputs.PARALLEL_THREADS}}"
        run: |
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export PATH=$ANDROID_HOME/tools:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          rm -rf homescapes_autotests
          git clone -b $AUTOTESTS_BRANCH git@github.com:Playrix/homescapes_autotests.git
          cd homescapes_autotests
          git show
          python3 -m venv venv
          source ./venv/bin/activate
          pyenv local 3.11.6
          eval "$(pyenv init -)"
          pip3 install --upgrade pip
          pip3 install -r ./requirements.txt
          pip3 install --extra-index-url https://nexus.local.playrix.com/repository/playrix-pypi/simple autotest_client==0.1.10 --no-deps
          mkdir app
          ./experimental/runTests.py --only-testing $ONLY_TESTING --platform $PLATFORM --retries $RETRIES --parallel-threads $PARALLEL_THREADS --teamcity-build-id 18408273 --teamcity-user mark-o --teamcity-pass FZBHvt38u10726\$4

