name: Homescapes UI Autotests
run-name: 🤖 Running Homescapes UI Autotests
on: 
  workflow_dispatch:
    inputs:     
      TEST_ENV: 
        description: Just for test
        default: "123456"
jobs:
  iOS-QA-CI-TF:
    strategy:
      matrix:
        runner: [aqa_hs_0]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: TestQaCI
        shell: bash -l {0}
        env: 
          LANG: "en_US.UTF-8"
          LANGUAG: "en_US.UTF-8"
          LC_ALL: "en_US.UTF-8"
          ANDROID_HOME: "~/Library/Android/sdk"          
          TEST_ENV: "${{github.event.inputs.TEST_ENV}}"
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed
          rm -rf homescapes_autotests
          git clone git@github.com:Playrix/homescapes_autotests.git
          cd homescapes_autotests
          pyenv local 3.11.6
          python -m venv venv
          source ./venv/bin/activate
          pip3 install --upgrade pip
          pip3 install -r ./requirements.txt
          pip3 install --extra-index-url https://nexus.local.playrix.com/repository/playrix-pypi/simple autotest_client==0.1.10 --no-deps
          ./experimental/runTests.py --only-testing 8075 --platform android --parallel-threads 1

