name: Homescapes UI Autotests
run-name: 🤖 Running Homescapes UI Autotests
on: 
  workflow_dispatch:
    inputs:     
      AUTOTESTS_BRANCH: 
        description: homescapes_autotests branch
        default: "main"
      
      TEAMCITY_BUILD_ID: 
        description: Teamcity build id
        default: ""    
      
      ONLY_TESTING:
        description: Only testing
        default: ""
      
      RETRIES: 
        description: Retries
        default: "3"
      
      PARALLEL_THREADS: 
        description: Parallel threads
        default: "1"

      TEST_RUN_ID:
        description: Test run id
        default: ""
        
      TMS_AUTO_EXPORT:
        description: Enable auto export in tms (QASE)
        default: "false"

      SEASON_TYPE: 
        description: Season type for season tests
        default: "last_season"

      EXPEDITION: 
        description: Expedition for exp tests
        default: "last_expedition"

      QASE_RUN_ID: 
        description: Existing qase run to join
        default: ""
        
jobs:
  PLR-HS-QA-AUTOTESTS:
    strategy:
      matrix:
        runner: [aqa_hs_0, aqa_hs_1, aqa_hs_2]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: TestQaCI
        shell: bash -l {0}
        env: 
          LANG: "en_US.UTF-8"
          LANGUAG: "en_US.UTF-8"
          LC_ALL: "en_US.UTF-8"
          AUTOTESTS_BRANCH: "${{github.event.inputs.AUTOTESTS_BRANCH}}"
          TEAMCITY_BUILD_ID: "${{github.event.inputs.TEAMCITY_BUILD_ID}}"
          PLATFORM: "android"
          ONLY_TESTING: "${{github.event.inputs.ONLY_TESTING}}"
          RETRIES: "${{github.event.inputs.RETRIES}}"
          PARALLEL_THREADS: "${{github.event.inputs.PARALLEL_THREADS}}"
          TEST_RUN_ID: "${{github.event.inputs.TEST_RUN_ID}}"
          TMS_AUTO_EXPORT: "${{github.event.inputs.TMS_AUTO_EXPORT}}"
          CALENDAR_API_TOKEN: "${{secrets.CALENDAR_API_TOKEN_SECRET}}"
          QASE_TESTOPS_API_TOKEN: "${{secrets.QASE_TESTOPS_API_TOKEN_SECRET}}"
          SEASON_TYPE: "${{github.event.inputs.SEASON_TYPE}}"
          EXPEDITION: "${{github.event.inputs.EXPEDITION}}"
          QASE_RUN_ID: "${{github.event.inputs.QASE_RUN_ID}}"
        run: |
          export ANDROID_HOME_OLD=$HOME/Library/Android/sdk
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$ANDROID_HOME/tools:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          rm -rf homescapes_autotests
          git clone --recursive -b $AUTOTESTS_BRANCH git@github.com:Playrix/homescapes_autotests.git
          cd homescapes_autotests
          git submodule update --init --recursive --remote
          git show
          python3 -m venv venv
          source ./venv/bin/activate
          pyenv local 3.11.6
          eval "$(pyenv init -)"
          pip3 install --upgrade pip
          pip3 install -r ./requirements.txt
          pip3 install -r ./homescapes_tools/requirements.txt
          pip3 install --extra-index-url https://nexus.local.playrix.com/repository/playrix-pypi/simple autotest_client==1.16.12 --no-deps
          mkdir app
          rm -rf ~/.android/avd && mkdir ~/.android/avd
          ./experimental/runTests.py --test-run-id "$TEST_RUN_ID" --only-testing "$ONLY_TESTING" --platform $PLATFORM --retries $RETRIES --parallel-threads $PARALLEL_THREADS --tms-auto-export $TMS_AUTO_EXPORT --teamcity-build-id $TEAMCITY_BUILD_ID --teamcity-user mark-o --teamcity-pass FZBHvt38u10726\$4 --season-type $SEASON_TYPE --expedition $EXPEDITION --qase-run-id "$QASE_RUN_ID"
